services:
  mongodb:
    image: mongo:7
    container_name: express_mongodb
    restart: unless-stopped

    environment:  
      MONGO_INITDB_ROOT_USERNAME: vira
      MONGO_INITDB_ROOT_PASSWORD: vira

    ports:
      - "27018:27017"

    volumes:
      - ecommerce_data:/data/db

volumes:
  ecommerce_data: